// SPDX-License-Identifier: Apache-2.0
// Part of MPAPP.

#include "mpapp_xc/diagnostics.hpp"
#include "mpapp_xc/emitter.hpp"
#include "mpapp_xc/parser.hpp"

// Generated by CMake: defines MPAPP_XC_FIXTURES_DIR and MPAPP_XC_EXE.
#include "test_paths.hpp"

#include <catch2/catch_test_macros.hpp>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>

#ifndef _WIN32
#include <sys/wait.h>
#endif

namespace fs = std::filesystem;

namespace {

std::string slurp(const fs::path& path) {
    std::ifstream stream{path, std::ios::binary};
    REQUIRE(stream);
    std::ostringstream buffer{};
    buffer << stream.rdbuf();
    return buffer.str();
}

// Normalize CRLF -> LF so file comparisons are platform-stable.
std::string normalize_eol(std::string s) {
    std::string out{};
    out.reserve(s.size());
    for (auto c : s) {
        if (c != '\r') out.push_back(c);
    }
    return out;
}

fs::path fixture(std::string_view name) {
    return fs::path{MPAPP_XC_FIXTURES_DIR} / name;
}

} // namespace

TEST_CASE("Empty XAML parses to a single root element", "[parser]") {
    const auto source = slurp(fixture("empty.xaml"));
    mpapp::xc::diagnostic_collector diags{};
    const auto doc = mpapp::xc::parse(source, fs::path{"empty.xaml"}, diags);

    REQUIRE(diags.empty());
    REQUIRE(doc.has_root);
    REQUIRE(doc.root.tag == "ContentPage");
    REQUIRE(doc.root.children.empty());

    REQUIRE(doc.default_xmlns.has_value());
    REQUIRE(*doc.default_xmlns == "http://schemas.microsoft.com/dotnet/2021/maui");
    REQUIRE(doc.x_namespace.has_value());
    REQUIRE(*doc.x_namespace == "http://schemas.microsoft.com/winfx/2009/xaml");
    REQUIRE(doc.x_class.has_value());
    REQUIRE(*doc.x_class == "MyApp.MainPage");
}

TEST_CASE("Emitter produces expected output for empty.xaml", "[emitter]") {
    const auto source = slurp(fixture("empty.xaml"));
    mpapp::xc::diagnostic_collector diags{};
    const auto doc = mpapp::xc::parse(source, fs::path{"empty.xaml"}, diags);
    REQUIRE(diags.empty());

    const auto actual = normalize_eol(mpapp::xc::emit(doc));
    const auto expected = normalize_eol(slurp(fixture("empty_expected.gen.hpp")));

    REQUIRE(actual == expected);
}

TEST_CASE("Diagnostic for unclosed tag points at the right line", "[parser][diagnostics]") {
    // Tag opens on line 3 and is never closed. pugixml should fail with an
    // offset pointing at or past line 3.
    const std::string source =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<ContentPage>\n"
        "    <Label\n";
    mpapp::xc::diagnostic_collector diags{};
    const auto doc = mpapp::xc::parse(source, fs::path{"broken.xaml"}, diags);

    REQUIRE(diags.has_errors());
    REQUIRE_FALSE(doc.has_root);

    const auto& first = diags.entries().front();
    REQUIRE(first.level == mpapp::xc::severity::error);
    REQUIRE(first.source_path == fs::path{"broken.xaml"});
    REQUIRE(first.line >= 3);
}

TEST_CASE("x:Class basename becomes the generated function name", "[emitter]") {
    REQUIRE(mpapp::xc::class_basename("MyApp.MainPage") == "MainPage");
    REQUIRE(mpapp::xc::class_basename("Nested.Sub.Page") == "Page");
    REQUIRE(mpapp::xc::class_basename("RootOnly") == "RootOnly");
    REQUIRE(mpapp::xc::class_basename("").empty());

    mpapp::xc::xaml_document doc{};
    doc.source_path = "thing.xaml";
    doc.has_root = true;
    doc.root.tag = "Window";
    doc.x_class = "Demo.AppShell.RootWindow";

    const auto generated = mpapp::xc::emit(doc);
    REQUIRE(generated.find("build_RootWindow(") != std::string::npos);
    REQUIRE(generated.find("<Window>") != std::string::npos);
}

TEST_CASE("Missing input file emits diagnostic, exits 2", "[cli]") {
    const std::string_view exe = MPAPP_XC_EXE;
    if (exe.empty()) {
        SUCCEED("mpapp-xc executable path not configured; skipping CLI test");
        return;
    }

    const auto missing = fs::temp_directory_path() / "mpapp-xc-no-such-file.xaml";
    std::error_code ec{};
    fs::remove(missing, ec);

    std::ostringstream cmd{};
#ifdef _WIN32
    // Wrap the whole command in an extra pair of quotes so cmd.exe's quoting
    // rules don't strip the inner quotes around a path with spaces.
    cmd << "\"\"" << exe << "\" \"" << missing.string() << "\"\"";
#else
    cmd << '"' << exe << "\" \"" << missing.string() << '"';
#endif

    const int raw = std::system(cmd.str().c_str());
#ifdef _WIN32
    const int code = raw;
#else
    const int code = (raw >= 0) ? WEXITSTATUS(raw) : raw;
#endif
    REQUIRE(code == 2);
}
