// SPDX-License-Identifier: Apache-2.0
// Part of MPAPP.
//
// Lowering test: runs the parser + emitter over counter_page.xaml and asserts
// the generated C++ contains the expected constructions, setters, and
// parent-child wiring against the real mpapp API surface.

#include "mpapp_xc/diagnostics.hpp"
#include "mpapp_xc/emitter.hpp"
#include "mpapp_xc/parser.hpp"

// Generated by CMake: defines MPAPP_XC_FIXTURES_DIR and MPAPP_XC_EXE.
#include "test_paths.hpp"

#include <catch2/catch_test_macros.hpp>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>

namespace fs = std::filesystem;

namespace {

std::string slurp(const fs::path& path) {
    std::ifstream stream{path, std::ios::binary};
    REQUIRE(stream);
    std::ostringstream buffer{};
    buffer << stream.rdbuf();
    return buffer.str();
}

fs::path fixture(std::string_view name) {
    return fs::path{MPAPP_XC_FIXTURES_DIR} / name;
}

bool contains(const std::string& haystack, std::string_view needle) {
    return haystack.find(needle) != std::string::npos;
}

std::string generate(const char* fixture_name) {
    const auto source = slurp(fixture(fixture_name));
    mpapp::xc::diagnostic_collector diags{};
    const auto doc = mpapp::xc::parse(source, fs::path{fixture_name}, diags);
    REQUIRE(diags.empty());
    REQUIRE(doc.has_root);
    return mpapp::xc::emit(doc);
}

} // namespace

TEST_CASE("counter_page.xaml lowers to the expected mpapp constructions", "[lowering]") {
    const auto out = generate("counter_page.xaml");

    SECTION("function + self-contained header scaffolding") {
        // References the real umbrella for traceability and pulls in the
        // precise cross-platform surface headers it uses.
        REQUIRE(contains(out, "<mpapp/mpapp.hpp>"));
        REQUIRE(contains(out, "#include <mpapp/internal/basic_content_page.hpp>"));
        REQUIRE(contains(out, "namespace mpapp::generated {"));
        REQUIRE(contains(out, "build_CounterPage()"));
    }

    SECTION("every element is constructed via make_shared of its mpapp type") {
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_content_page>()"));
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_stack_layout>()"));
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_label>()"));
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_entry>()"));
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_switch_>()"));
        REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_button>()"));
    }

    SECTION("attribute setters lower with correct value types") {
        REQUIRE(contains(out, "->text = \"Counter\""));
        REQUIRE(contains(out, "->font_size = 24.0"));
        REQUIRE(contains(out, "->placeholder = \"Type here\""));
        REQUIRE(contains(out, "->is_on = true"));
        REQUIRE(contains(out, "->text = \"Increment\""));
        REQUIRE(contains(out, "->spacing = 12.0"));
        REQUIRE(contains(out, "->padding = mpapp::thickness{24}"));
    }

    SECTION("parent-child wiring uses add() for layouts and content for pages") {
        REQUIRE(contains(out, "->content = e1"));   // page content <- stack layout
        REQUIRE(contains(out, "->add(*e2)"));        // stack layout <- label
    }

    SECTION("#line directives map back to the XAML source") {
        REQUIRE(contains(out, "\"counter_page.xaml\""));
        REQUIRE(contains(out, "#line "));
    }
}

TEST_CASE("empty.xaml still lowers to a compilable stub root", "[lowering]") {
    const auto out = generate("empty.xaml");
    REQUIRE(contains(out, "build_MainPage()"));
    REQUIRE(contains(out, "std::make_shared<mpapp::internal::basic_content_page>()"));
    REQUIRE(contains(out, "return e0;"));
}
