// SPDX-License-Identifier: Apache-2.0
// Part of MPAPP.

#include "mpapp_xc/emitter.hpp"

#include <sstream>
#include <string>

namespace mpapp::xc {

namespace {

// Fallback used when the parser couldn't determine where the root opened.
// Matches the typical "XML decl on line 1, root on line 2" XAML shape.
constexpr std::ptrdiff_t root_line_fallback = 2;

std::string source_filename_for(const xaml_document& doc, const emit_options& options) {
    if (!options.source_filename.empty()) return options.source_filename;
    if (doc.source_path.has_filename()) return doc.source_path.filename().string();
    return doc.source_path.string();
}

} // namespace

std::string emit(const xaml_document& doc, const emit_options& options) {
    const std::string source_filename = source_filename_for(doc, options);
    const std::string input_display =
        doc.source_path.empty() ? source_filename : doc.source_path.generic_string();

    const std::string fn_name = [&] {
        const auto base = doc.x_class.has_value() ? class_basename(*doc.x_class) : std::string{};
        return base.empty() ? std::string{"anonymous"} : base;
    }();

    const std::string root_tag = doc.has_root && !doc.root.tag.empty() ? doc.root.tag : "unknown";
    const auto root_line = doc.root_line > 0 ? doc.root_line : root_line_fallback;

    std::ostringstream os;
    os << "// Auto-generated by mpapp-xc from " << input_display << '\n';
    os << "// DO NOT EDIT.\n";
    os << '\n';
    os << "#pragma once\n";
    os << '\n';
    os << "#include <mpapp/mpapp.hpp>\n";
    os << '\n';
    os << "namespace mpapp::generated {\n";
    os << '\n';
    os << "#line " << root_line << " \"" << source_filename << "\"\n";
    os << "consteval auto build_" << fn_name << "() {\n";
    os << "    // TODO: emit children. Skeleton P0 only emits the root.\n";
    os << "    return /* stub: empty visual tree for <" << root_tag << "> */ 0;\n";
    os << "}\n";
    os << '\n';
    os << "} // namespace mpapp::generated\n";

    return os.str();
}

} // namespace mpapp::xc
