// SPDX-License-Identifier: Apache-2.0
// Part of MPAPP. Cross-platform umbrella header for `window_handler`.
//
// Generated by tools/dev/generate-handler-umbrellas.py (run from repo
// root). Do not edit by hand — re-run the generator after adding or
// removing per-platform handler files.
//
// Usage:
//   #include <mpapp/handlers/window_handler.hpp>
//   mpapp::window_handler<mpapp::platform::current> handler_{};
//
// The umbrella dispatches via `__has_include` to the per-platform header
// matching the build target. Platforms without an implementation yet
// emit a clear `#error` rather than a missing-header diagnostic.

#ifndef MPAPP_HANDLERS_WINDOW_HANDLER_HPP
#define MPAPP_HANDLERS_WINDOW_HANDLER_HPP

#if defined(_WIN32)
#  if __has_include(<mpapp/handlers/windows/window_handler.hpp>)
#    include <mpapp/handlers/windows/window_handler.hpp>
#  else
#    error "mpapp::window_handler<platform::windows> not implemented yet."
#  endif
#elif defined(__ANDROID__)
#  if __has_include(<mpapp/handlers/android/window_handler.hpp>)
#    include <mpapp/handlers/android/window_handler.hpp>
#  else
#    error "mpapp::window_handler<platform::android> not implemented yet."
#  endif
#elif defined(__APPLE__)
#  include <TargetConditionals.h>
#  if TARGET_OS_IPHONE
#    if __has_include(<mpapp/handlers/ios/window_handler.hpp>)
#      include <mpapp/handlers/ios/window_handler.hpp>
#    else
#      error "mpapp::window_handler<platform::ios> not implemented yet — pending M-08."
#    endif
#  else
#    if __has_include(<mpapp/handlers/macos/window_handler.hpp>)
#      include <mpapp/handlers/macos/window_handler.hpp>
#    else
#      error "mpapp::window_handler<platform::macos> not implemented yet — pending M-07."
#    endif
#  endif
#elif defined(__linux__)
#  if __has_include(<mpapp/handlers/linux/window_handler.hpp>)
#    include <mpapp/handlers/linux/window_handler.hpp>
#  else
#    error "mpapp::window_handler<platform::linux_> not implemented yet."
#  endif
#else
#  error "MPAPP: unsupported host platform — no `mpapp::window_handler` available."
#endif

#endif // MPAPP_HANDLERS_WINDOW_HANDLER_HPP
