#!/usr/bin/env python3
"""
Generate `include/mpapp/handlers/<name>.hpp` umbrella headers that
auto-include the per-platform handler header matching the build target.

Union of all per-platform handler headers under
include/mpapp/handlers/{windows,linux,android,macos,ios}/. Each umbrella
uses `__has_include` so platforms missing a particular handler get a
helpful `#error` instead of a cryptic missing-file diagnostic.

Idempotent — overwrites existing umbrellas with the same content.

Run from repo root.
"""
import os, sys, re

REPO = "D:/GitHub/MPAPP"
HANDLERS = os.path.join(REPO, "include/mpapp/handlers")

PLATFORMS = ["windows", "linux", "android", "macos", "ios"]

def collect_handlers():
    """Return the union of handler-header basenames across all per-platform dirs."""
    s = set()
    for plat in PLATFORMS:
        d = os.path.join(HANDLERS, plat)
        if not os.path.isdir(d): continue
        for fn in os.listdir(d):
            if fn.endswith(".hpp"):
                s.add(fn)
    return sorted(s)

# Files that are platform-internal infrastructure (not cross-platform
# component handlers) — keep them per-platform, no umbrella generated.
PLATFORM_INTERNAL = {"jni_bridge.hpp"}

UMBRELLA_TEMPLATE = """// SPDX-License-Identifier: Apache-2.0
// Part of MPAPP. Cross-platform umbrella header for `{stem}`.
//
// Generated by tools/dev/generate-handler-umbrellas.py (run from repo
// root). Do not edit by hand — re-run the generator after adding or
// removing per-platform handler files.
//
// Usage:
//   #include <mpapp/handlers/{file}>
//   mpapp::{stem}<mpapp::platform::current> handler_{{}};
//
// The umbrella dispatches via `__has_include` to the per-platform header
// matching the build target. Platforms without an implementation yet
// emit a clear `#error` rather than a missing-header diagnostic.

#ifndef MPAPP_HANDLERS_{guard}_HPP
#define MPAPP_HANDLERS_{guard}_HPP

#if defined(_WIN32)
#  if __has_include(<mpapp/handlers/windows/{file}>)
#    include <mpapp/handlers/windows/{file}>
#  else
#    error "mpapp::{stem}<platform::windows> not implemented yet."
#  endif
#elif defined(__ANDROID__)
#  if __has_include(<mpapp/handlers/android/{file}>)
#    include <mpapp/handlers/android/{file}>
#  else
#    error "mpapp::{stem}<platform::android> not implemented yet."
#  endif
#elif defined(__APPLE__)
#  include <TargetConditionals.h>
#  if TARGET_OS_IPHONE
#    if __has_include(<mpapp/handlers/ios/{file}>)
#      include <mpapp/handlers/ios/{file}>
#    else
#      error "mpapp::{stem}<platform::ios> not implemented yet — pending M-08."
#    endif
#  else
#    if __has_include(<mpapp/handlers/macos/{file}>)
#      include <mpapp/handlers/macos/{file}>
#    else
#      error "mpapp::{stem}<platform::macos> not implemented yet — pending M-07."
#    endif
#  endif
#elif defined(__linux__)
#  if __has_include(<mpapp/handlers/linux/{file}>)
#    include <mpapp/handlers/linux/{file}>
#  else
#    error "mpapp::{stem}<platform::linux_> not implemented yet."
#  endif
#else
#  error "MPAPP: unsupported host platform — no `mpapp::{stem}` available."
#endif

#endif // MPAPP_HANDLERS_{guard}_HPP
"""

def main():
    handlers = collect_handlers()
    written = 0
    skipped_internal = 0
    for h in handlers:
        if h in PLATFORM_INTERNAL:
            skipped_internal += 1
            continue
        stem = h[:-len(".hpp")]              # button_handler
        guard = stem.upper()                  # BUTTON_HANDLER
        out = os.path.join(HANDLERS, h)
        body = UMBRELLA_TEMPLATE.format(file=h, stem=stem, guard=guard)
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
        written += 1
    print(f"wrote {written} umbrella headers in {HANDLERS}/")
    print(f"skipped {skipped_internal} platform-internal headers (jni_bridge, etc.)")

if __name__ == "__main__":
    main()
