// Auto-generated by mpapp-xc from empty.xaml
// DO NOT EDIT.

#pragma once

#include <mpapp/mpapp.hpp>

namespace mpapp::generated {

#line 2 "empty.xaml"
consteval auto build_MainPage() {
    // TODO: emit children. Skeleton P0 only emits the root.
    return /* stub: empty visual tree for <ContentPage> */ 0;
}

} // namespace mpapp::generated
